R/SDA_query.R

Implements change suggested in https://github.com/ncss-tech/soilDB/issues/106

Avoid i/o of JSON form at the start of `SDA_query`

---

R/fetchNASIS_pedons.R
R/get_extended_data_from_NASIS_db.R
R/humanArtifacts.R
R/simplfyFragmentData.R
tests/testthat/test-simplifyArtifactData.R

This is a shameless ripoff of simplifyFragmentData() in all its glory ;)
This was helpful for me to learn a bit more about how the flattening steps work in the fetch functions.  I saw some opportunities for generalizing these approaches going forward.
Feature requested by Sarah Smith & Kristine Ryan in the 11-AUR office.
Please test it out. 
```r
remotes::install_github(“ncss-tech/soilDB@anthro”, 
dependencies=FALSE, upgrade=FALSE, build=FALSE)
```
Splits flat versus all other shapes to determine volume in channer and flag (art_ch, art_fl) size classes
> art_fgr, art_gr, art_cb, art_st, art_by, art_ch, art_fl, art_unspecified
> total_art_pct, huartvol_cohesive, huartvol_penetrable, huartvol_innocuous, huartvol_persistent
For instance, `total_art_pct` is the total volume of artifacts in a …

adding basic support for human artifact summaries in fetchNASIS_pedons()

---

R/simplifyArtifactData.R
tests/testthat/test-simplifyArtifactData.R

simplifyArtifactData now respects id.var when calculating the subtotal summary values for cohesive, noxious, persistent, etc.; 
also renamed phhuart_inocuous -> phhuart_noxious for parity with other summary subtotals; added new tests that catch a case I had neglected to test.
Thanks to Sarah Smith for showing the output that made me realize my mistake.

fix for subtotals greater than 100%

---

R/fetchNASIS.R
R/fetchNASIS_components.R
R/fetchNASIS_pedons.R
R/fetchNASIS_report.R
R/get_component_from_SDA.R
man/fetchNASIS.Rd
man/fetchSDA_component.Rd
man/get_comonth_from_NASIS_db.Rd
man/get_component_data_from_NASIS_db.Rd
man/uncode.Rd
tests/testthat/test-fetchSDA_component.R

As discussed I demoted fetchNASIS_pedons() and fetchNASIS_components to internal functions. They will no longer show up in the list of soilDB functions or help files.

demoting fetchNASIS_pedons() and fetchNASIS_components() to internal functions

---

R/SDA-spatial.R
man/SDA_spatialQuery.Rd
tests/testthat/test-SDA_query.R

- addressing issue #141
- function `SDA_spatialQuery()` gains new argument `db` to select whether geometries should be queried from Soil Geographic Database SSURGO or STATSGO
- default value of `db` is "SSURGO"; the new argument is backwards compatible
- updated roxygen-style function documentation in source file and in man/*.Rd object
- updated unit tests to include a simple check for the new argument with default ("SSURGO") and new "STATSGO" values

Function `SDA_spatialQuery()` gains new argument `db`

---

R/dbQueryNASIS.R
R/fetchNASIS.R
R/fetchNASIS_pedons.R
R/get_RMF_from_NASIS_db.R
R/get_colors_from_NASIS_db.R
R/get_component_data_from_NASIS_db.R
R/get_concentrations_from_NASIS_db.R
R/get_cosoilmoist_from_NASIS.R
R/get_extended_data_from_NASIS_db.R
R/get_hz_data_from_NASIS_db.R
R/get_lablayer_data_from_NASIS_db.R
R/get_labpedon_data_from_NASIS_db.R
R/get_phfmp_from_NASIS_db.R
R/get_phlabresults_data_from_NASIS_db.R
R/get_projectmapunit_from_NASIS.R
R/get_site_data_from_NASIS_db.R
R/get_soilseries_from_NASIS.R
R/get_text_notes_from_NASIS_db.R
R/get_veg_data_from_NASIS_db.R
R/get_vegplot_data_from_NASIS_db.R
R/openNASISchannel.R
R/uncode.R
man/dbConnectNASIS.Rd
man/fetchNASIS.Rd
misc/NASIS-lite.R
misc/validate-NASIS-results.R

This PR implements the argument for a local SQLite file from `fetchNASIS` down through the lower level methods, on to the `dbConnectNASIS()` calls. 
This is cherry-picked so none of the special modifications made for using the (slightly different from NASIS internal) NASIS pedon snapshot (RE: nasisLITE branch) are included. All local NASIS tests and validations (see script in /misc/  made for nasisDBI) are passing.

NASIS DBI interface to SQLite static (local file) database

---

R/WCS-utils.R
R/mukey-WCS.R
man/mukey.wcs.Rd
misc/WCS-SDA-example.R
tests/testthat/test-mukey-WCS.R

These commits are grouped so @dylanbeaudette can take 'em or leave em.
1. proj4 safe examples -- not controversial
2. reverse order of db and aoi arguments -- does not affect example, I think aoi in first position is more pipe friendly and is just my preference
3. add sf support; this passes R CMD CHECK -- we already have sf in suggests; appears to be equivalent to list-based
4. very small extent test; downloads something like 500 bytes of data from WCS

minor enhancements for WCS SSURGO MUKEY interface

---

R/fetchSCAN.R

The `stop()` call seems to not be needed anymore. Works fine on 32-bit R 4.0.2
```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 10 x64 (build 18363)
Matrix products: default
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] plyr_1.8.6
loaded via a namespace (and not attached):
[1] Rcpp_1.0.6        cluster_2.1.0     knitr_1.30        xml2_1.3.2       
[5] raster_3.4-5      magrittr_2.0.1    rvest_0.3.6       lattice_0.20-41  
[9] R6_2.5.0 …
```

SCAN_sensor_metadata works in 32-bit R

---

R/SDA_interpretations.R
R/SDA_properties.R
man/get_SDA_interpretation.Rd
man/get_SDA_property.Rd
misc/NASIS-ssurgo-export-tools/ssurgo-export.R
tests/testthat/test-SDA_interpretations.R
tests/testthat/test-SDA_properties.R

Working on some new tools for interp validations in southwest region and intend to be using the new ssurgoOnDemand `get_SDA*` functions for handling some of the comparisons to "live" SSURGO. Here is my first cut at extending these things beyond the standard "mukey" and "areasymbol" and mapunit-level aggregation methods.
I am considering ways to further improve and manipulate the output for higher-level purposes (i.e. some sort of `fetch*` function) and I expect new aggregation methods and options will be added to the ones that have already been implemented to improve parity with WSS and more.
Perhaps the most generic case of "aggregation" is to return _un-aggregated_ component (or horizon) data back to the user. This is especially helpful when trying to interpret "Dominant Condition" …

get_SDA_interpretation/get_SDA_property: Add "NONE" aggregation method and improve details for arguments

---

DESCRIPTION
NEWS.md
R/ISSR800.R
R/mukey-WCS.R
R/parseWebReport.R
README.Rmd
man/ISSR800.wcs.Rd
man/mukey.wcs.Rd
tests/testthat/test-ISSR800.R
tests/testthat/test-mukey-WCS.R

It appears that a couple tests of the WCS functionality are erroring out on new M1 Mac platform. Need to fail gracefully. 
https://www.stats.ox.ac.uk/pub/bdr/M1mac/soilDB.out
- I have replaced a hard `stop()` on "bad WCS request" in `ISSR800.wcs` and `mukey.wcs` with a message and a try-error result.  
- The documentation has been updated to reflect that a `try-error` will be returned when WCS fails. 
- Tests are skipped if offline and on CRAN
- Test expectations have been updated to handle possible outputs under a failed WCS request (if for some reason tests fail to be skipped)
I will be making a submission to CRAN by end of today to correct it.

CRAN Release 2.6.2

---

R/SDA_hydric.R
R/SDA_interpretations.R
R/SDA_properties.R
man/get_SDA_interpretation.Rd
man/get_SDA_property.Rd
misc/getSDA_vectorize.R
misc/soil-data-aggregation/get_SDA_SOD-tests.R
tests/testthat/test-SDA_interpretations.R
tests/testthat/test-SDA_properties.R

- Extends `get_SDA_property(property = ...)` and `get_SDA_interpretation(rulename = ...)` vectorization over property/rulename to work with any aggregation method. Now supports: Dominant Condition, Min/Max, Dominant Component, Weighted Average
- Previously vector length > 1 properties or interpretations could be passed only for `method = "NONE"` (no aggregation)
- Add `query_string` argument (default: `FALSE`). Set as `TRUE` to skip submitting query to SDA returning a string of the query that would have been sent instead of _data.frame_ result
- Standardizing `MUKEY` column name (and other keys) as _lowercase_ in results (and subqueries) 
- More informative error messages for bad input / arguments inconsistent with specified `method`
- Updated docs
- `get_SDA_property`: Remove `ISNULL(x, …

Updates to `get_SDA_*` / SOD-like methods

---

NAMESPACE
NEWS.md
R/SDA_query.R
R/fetchSDA_spatial.R
man/fetchSDA_spatial.Rd
misc/SOD-wt-mean-check.R
tests/testthat/test-SDA_query.R
tests/testthat/test-fetchSDA_component.R
tests/testthat/test-fetchSDA_spatial.R

All tests and R CMD check passing on my local machine. I'm a little concerned that I may have missed an important SQL Server datatype in the conversion code. This style of conversion is not robust to arbitrary use of CAST(xxx AS `SOMEOTHERDATATYPE`) that hasn't been included in the following `swtich()`:
```r
cc <- sapply(m, function(j) {
dt <- strsplit(j, split = ',', fixed = TRUE)[[1]][8]
switch(dt,
'DataTypeName=char' = 'character',
'DataTypeName=varchar' = 'character',
'DataTypeName=nvarchar' = 'character',
'DataTypeName=datetime' = 'character',
'DataTypeName=int' = 'integer',
'DataTypeName=smallint' = 'integer',
'DataTypeName=real' = 'numeric',
'DataTypeName=float' = 'numeric',
'DataTypeName=decimal' = 'numeric'
)
})
idx <- which(cc != 'character')
for(f in idx) {
df[, f] <- as(df[, …
```

first cut at a solution to #190 and more generally, a formal connection to datatypes as used in SDA

---

R/fetchNASIS_pedons.R
R/get_phlabresults_data_from_NASIS_db.R

Thanks to @hammerly who pointed out that weighted averaging of phlabresults wasn't working as expected and for highlighting some more possible improvements.
For examples, load upedonid: 1964IA113001, 1975IA045012.
Before:
``` r
f <- soilDB::fetchNASIS(rmHzErrors = TRUE, lab = TRUE)
#> Loading required namespace: odbc
#> mixing moist colors ... [14 of 42 horizons]
#> Warning: some records are missing rock fragment volume, these have been removed
#> Warning: all records are missing rock fragment volume (NULL). buffering result
#> with NA. will be converted to zero if nullFragsAreZero = TRUE.
#> Warning: some records are missing artifact volume, these have been removed
#> Warning: all records are missing artifact volume (NULL). buffering result with
#> NA. will be converted to zero if …
```

get_phlabresults_data_from_NASIS_db(): Fix the weighted average of multiple records per horizon

---

R/SDA-spatial.R
man/SDA_spatialQuery.Rd
tests/testthat/test-SDA_query.R

This PR adds support in `SDA_spatialQuery()` to get results from the `sapolygon` table. Works with both "intersection" and "overlap" methods.
For example -- get all survey areas in MLRA 22A, using the MLRA boundary as `geom` "query feature"
``` r
library(sp)
mlra <- rgdal::readOGR("F:/Geodata/soils/MLRA_Boundaries_CA/mlra_a_ca.shp")
#> OGR data source with driver: ESRI Shapefile 
#> Source: "F:\Geodata\soils\MLRA_Boundaries_CA\mlra_a_ca.shp", layer: "mlra_a_ca"
#> with 59 features
#> It has 12 fields
#> Integer64 fields read as strings:  OBJECTID_1 OBJECTID
mlra <- spTransform(mlra, "EPSG:4326")
mlra22a <- subset(mlra, MLRARSYM == "22A")
res1 <- SDA_spatialQuery(mlra22a, what = "areasymbol")
res2 <- SDA_spatialQuery(mlra22a, what = "sapolygon")
res3 <- …
```

 SDA_spatialQuery: add support for sapolygon/areasymbol results

---

DESCRIPTION
NEWS.md
R/fetchNASIS.R
R/fetchNASIS_pedons.R
R/get_hz_data_from_NASIS_db.R
man/fetchNASIS.Rd
man/get_hz_data_from_NASIS_db.Rd
tests/testthat/test-fetchNASIS.R

Closes #131; thanks to request from Julie Baker in 2-SON office
Having any depths be `NA` is an aqp/SoilProfileCollection depth logic error. Currently `fetchNASIS()` component filling checks for NA  `chiid` to identify permissible logic errors when `fill=TRUE` and `rmHzErrors=TRUE`. In the case of a "filled" SPC, it is not possible to set the unique horizon ID name because NA values are not allowed. Uses the default `hzID` integer calculated by aqp using ID-topdepth order.
Users of SoilProfileCollections must be aware of the need to check logic of the profiles in the collection before running relevant analyses. They can do this same way as is done in `fetchNASIS()` with `aqp::checkHzDepthLogic()`. Basic SPC operations, including `horizons<-` left join should work correctly in a filled …

fetchNASIS: Implement `fill` argument for NASIS pedons

---

R/createStaticNASIS.R

Column order should match NASIS, even if datatypes require reorder for ODBC driver / query. Thanks to @jskovlin who saw something and said something. This was a one-liner fix.
For background some versions of Microsoft ODBC driver require re-ordering of "long data" columns such that they occur last in the SELECT statement. With the default column orders in NASIS  `SELECT * FROM table` cannot be used for any table that contains a text field when the driver is {odbc} https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/getting-long-data?view=sql-server-ver15
For instance:
Microsoft ODBC Driver (_**SQL Server Native Client 11.0**_):
```r
soilDB::dbQueryNASIS(soilDB::NASIS(), "SELECT * FROM sitetext")
#> Loading required namespace: odbc
#> Error in result_fetch(res@ptr, n): …
```

createStaticNASIS / .dump_NASIS_table: column order 

---

DESCRIPTION
NEWS.md
R/SDA_hydric.R
R/SDA_pmgroupname.R
man/get_SDA_hydric.Rd
man/get_SDA_pmgroupname.Rd
tests/testthat/test-SDA_hydric.R
tests/testthat/test-SDA_pmgroupname.R

`get_SDA_pmgroupname()`: added support for alternate aggregation methods (dominant condition, none)
- also: fix bug with "mixed" -> "miscellaneous deposits" having too high of precedence
`get_SDA_hydric()`: overhauled logic to use component _percentage_ not _counts_, and added better explanation of derived mapunit-level classes. Also support alternate aggregation methods (dominant component, dominant condition, none)
The default classes for `method="MAPUNIT"` are as follows:
- `'Nonhydric'` - no hydric components
- `'Hydric'` - all hydric components
- `'Predominantly Hydric'` - hydric component percentage is 50% or more
- `'Partially Hydric'` - one or more of the major components is hydric
- `'Predominantly Nonhydric'` - hydric component percentage is less than 50%
Added `query_string` …

`get_SDA_pmgroupname()` and `get_SDA_hydric()` updates

---

NAMESPACE
R/get_OSD.R

This PR adds support for the `na = 'string'` argument for `toJSON()` that will be new format (https://github.com/ncss-tech/SoilKnowledgeBase/pull/37) for missing data in SoilKnowledgeBase repo parsed OSD JSON. This addresses my concerns about type stability discussed in ncss-tech/SoilKnowledgeBase#35
Before:
``` r
x <- soilDB::get_OSD("AABAB", base_url = 'https://raw.githubusercontent.com/ncss-tech/SoilKnowledgeBase/1cdb0f08b1fd178a61e510837f024501d1bd94a1/inst/extdata/OSD')
#> Loading required namespace: jsonlite
str(x$HORIZONS)
#> List of 1
#>  $ :'data.frame':    7 obs. of  16 variables:
#>   ..$ name         : chr [1:7] "Oi" "A1" "A2" "Bw1" ...
#>   ..$ top          : int [1:7] 0 3 10 30 48 56 112
#>   ..$ bottom       : int [1:7] 3 10 30 48 56 112 155
#>   ..$ dry_hue      : chr …
```

get_OSD: Handle "NA" and type conversion  

---

R/SDA_properties.R
man/get_SDA_property.Rd

Closes #219
Resolves 3 issues brought up by @dylanbeaudette's example:
---
```{r}
mu <- '623426'
get_SDA_property(property = c('sandtotal_r','claytotal_r'), method = 'NONE', mukeys = mu)
#>   areasymbol musym                                                  muname
#> 1      OK113    31 Braman silt loam, 0 to 1 percent slopes, rarely flooded
#> 2      OK113    31 Braman silt loam, 0 to 1 percent slopes, rarely flooded
#> 3      OK113    31 Braman silt loam, 0 to 1 percent slopes, rarely flooded
#> 4      OK113    31 Braman silt loam, 0 to 1 percent slopes, rarely flooded
#> 5      OK113    31 Braman silt loam, 0 to 1 percent slopes, rarely flooded
#>    mukey    cokey    chkey compname comppct_r hzdept_r hzdepb_r sandtotal_r
#> 1 623426 20848343 61342444   Braman        80 …
```

get_SDA_property: MIN/MAX aggregation fixes

---

NEWS.md
R/SDA-spatial.R
R/SDA_coecoclass.R
R/SDA_query.R
R/SSURGO_spatial_query.R
R/mapunit_geom_by_ll_bbox.R
man/SDA_query.Rd
man/SDA_spatialQuery.Rd
man/SoilWeb_spatial_query.Rd
man/mapunit_geom_by_ll_bbox.Rd
man/processSDA_WKT.Rd

- Update docs
- Use {sf} internally for all SDA spatial processing (with full {sp} support)
- Simplify `get_SDA_coecoclass()` results
- `mapunit_geom_by_ll_bbox()` is deprecated; see example in `?SDA_spatialQuery` for getting SDA mapunit polygon geometry from SSURGO, STATSGO or SAPOLYGON using a WGS84 longitude/latitude bounding box

SDA function cleanup

---

R/waterDayYear.R

Finally this will allow us to resolve binary build missing on r-release-macos-arm64 platform (broken since v2.6.5 on CRAN...)
Took me long enough to test this properly after blindly hacking away over the past several releases.
```r
waterDayYearTest <- function(x, tz) {
tzorig <- Sys.getenv("TZ")
Sys.setenv(TZ = tz)
x <- soilDB::waterDayYear(x, format = "%Y-%m-%d %H:%M:%S", tz = "UTC")
Sys.setenv(TZ = tzorig)
x$wd
}
```
```r
waterDayYearTest <- function(x, tz) {
tzorig <- Sys.getenv("TZ")
Sys.setenv(TZ = tz)
x <- soilDB::waterDayYear(x, format = "%Y-%m-%d %H:%M:%S", tz = "UTC")
Sys.setenv(TZ = tzorig)
x$wd
}
res <- sapply(OlsonNames(), function(x) waterDayYearTest("2000-12-05 12:00:00", x))
which(res != 66)
#>    Antarctica/McMurdo Antarctica/South_Pole            Etc/GMT-13 
#> …
```

Fix waterDayYear for CRAN

---

NEWS.md
R/fetchNASIS.R
R/fetchNASIS_components.R
R/get_component_data_from_NASIS_db.R
man/fetchNASIS.Rd

Many mapunits. Uses `get_component_correlation_data_from_NASIS_db()`, provides `dropAdditional` `dropNonRepresentative` and `duplicates` as optional arguments to `fetchNASIS()`. Creates a non-standard "coiidcmb" from the combination of `lmapunitiid:muiid:dmuiid:coiid` which is used as the result SPC ID column.
This seems to now be working as I intended after checking to make sure all joins have an appropriate ID on left and right hand side.

fetchNASIS("components"): use `duplicates` argument and custom profile ID for many:1 relationships of legend, mapunit to datamapunit

---

R/fetchKSSL.R

Thanks to Ben Marshall @Kramdog for bringing this up / reminding me that the SSL verification was still an issue in some cases. Since jsonlite changed behind the scenes, we need to attend to fetchKSSL-related downloads.
This updates `fetchKSSL()` to use {curl} internally for downloading the gzipped JSON from SoilWeb. This was what was done implicitly w/ `fromJSON()` w/ jsonlite <1.8.1, but with the `ssl_verifyhost` option set in the header.
While the base R approach / default headers included in jsonlite >1.8.1 work fine on non-gov machines we occasionally encounter errors related to SSL verification when in the office or connected to VPN, i.e.
Since we recently set up {curl}-based approach for replacing `download.file()` (due to timeout and SSL limitations), we just need to use the …

fetchKSSL: Fix for "status was 'SSL connect error'"

---

R/get_NASIS_table_name_by_purpose.R
R/get_site_data_from_NASIS_db.R
R/utils.R

This PR extends `fetchNASIS('pedons')` and `get_site_data_from_NASIS_db()` to use `.formatOtherVegString()` on the _siteothvegclass_ table if records are present in the selected set/local database
- adds `othvegclass` and `siteothvegclass` to default "lookup" and "site" sets via `get_NASIS_table_name_by_purpose()`

get_site_data_from_NASIS_db: Add siteothvegclass id/name

---

R/get_SDA_coecoclass.R
R/get_SDA_cosurfmorph.R
R/get_SDA_interpretation.R
R/get_SDA_pmgroupname.R
man/get_SDA_coecoclass.Rd
man/get_SDA_cosurfmorph.Rd
man/get_SDA_pmgroupname.Rd
tests/testthat/test-get_SDA_pmgroupname.R

- `get_SDA_pmgroupname()`: support for including or excluding misc. areas via `miscellaneous_areas` argument
- `get_SDA_cosurfmorph()`: add `miscellaneous_areas`

Improving support for `get_SDA*()` component filters

---

R/get_vegplot_data_from_NASIS_db.R

This branch has been open and needing to be merged for some time.
I generally am in favor of LEFT joins in this type of situation so that empty records can be diagnosed/QC'd and child table results are more complete
Thanks to @natearoe for suggestion

fetchVegdata: LEFT join to plant table

---

R/get_component_data_from_NASIS_db.R

This closes a long-standing issue #31.
For quality control and completeness reasons, LEFT joins work better in this context as all component IDs are included in the results. While INNER and LEFT join results are both safely joined into `fetchNASIS()` result regardless, users of the lower-level functions (or those doing QC directly on those results) will benefit from this change.
See also https://github.com/ncss-tech/soilDB/pull/287

Use LEFT join for component parent material and geomorph

---

R/get_component_from_SDA.R
vignettes/wcs-ssurgo.Rmd

based on @dylanbeaudette's tutorial http://ncss-tech.github.io/AQP/soilDB/WCS-demonstration-01.html
for #263
TODO:
- link out to `get_SDA*()` function specific vignette for better detail on tabular data acquisition
A couple things I noticed... not causing issues internally, but may cause confusion for users. Dylan mentioned ordered factor issue recently and now I experienced it with some of the examples i.e. Concrete Corrosion.

Add draft WCS vignette 

---

R/SDA_query.R
R/get_SDA_muaggatt.R
vignettes/wcs-ssurgo.Rmd

Fix 
- SDA_query error handling
- mukey column muaggatt table

Fix some SDA-related errors

---

NEWS.md
R/fetchSDA_spatial.R
man/fetchSDA_spatial.Rd

`fetchSDA_spatial()`: add `geom.src='mlrapolygon'` for querying MLRA boundaries by MLRARSYM
- currently `mlrapolygon` is not a SSURGO table, but the official ZIP file can be queried directly via GDAL using MLRARSYM as the query attribute
- in the future, if SDA ever provides MLRA geometry, the GDAL /vsizip/ method will be replaced with a T-SQL equivalent (and full support for other agg methods wil be added)
TODO:

fetchSDA_spatial: add `geom.src='mlrapolygon'` 

---

R/get_SDA_interpretation.R
man/get_SDA_interpretation.Rd

Adds subrule ratings to "reason" fields calculated for each `mrulename` in a `get_SDA_interpretation()` query. 
This helps get key information about subrules that are exported in cointerp with `ruledepth > 0` 
TODO:
- could pack an optional XML column containing arbitrary complexity about subrules 
Will close #303
Note the "reason" field now includes the `interphr` as well as `interphrc` values for rules with ruledepth != 0
``` r
x <- get_SDA_interpretation(rulename  = "NCCPI - National Commodity Crop Productivity Index (Ver 3.0)",
method     = "Dominant Component",
mukeys     = c("242963","242964","242965"))
x
#>    mukey    cokey areasymbol musym
#> 1 242963 23671045      IL019  152A
#> 2 242964 23670915      IL019  134A
#> 3 242965 23671016      IL019  154A
#> …
```

`get_SDA_interpretation()`: add subrule ratings to "reason" field

---

R/mukey-WCS.R

Fix for #304, issue raised by @kevinwolz who provided example AOI in that issue from the FL keys
Uses `terra::as.factor()` for result that has categorical representation of mukey (resolves TODO)
```r
library(sf)
setwd("~/workspace/gh/soilDB/304")
aoi <- sf::st_read("/vsizip/aoi_FL_keys.kml.zip")
#> Reading layer `aoi_FL_keys' from data source `/vsizip/aoi_FL_keys.kml.zip' using driver `KML'
#> Simple feature collection with 1 feature and 2 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -82.32659 ymin: 24.47644 xmax: -81.97248 ymax: 24.75134
#> Geodetic CRS:  WGS 84
res <- soilDB::mukey.wcs(aoi = aoi, db = "gssurgo", res = 30, quiet = FALSE)
#> Warning: expected 1167 rows, received 893; Y resolution may be affected. Try
#> requesting a smaller …
```

`mukey.wcs()`: fix areas containing all NoData and resolution for AOI at edge of WCS extent

---

DESCRIPTION
NEWS.md
R/SSURGO_query.R
R/get_SDA_coecoclass.R
man/get_SDA_coecoclass.Rd

The method performs a condition-based aggregation for each ecological site condition in the map unit, producing a "wide" data.frame result with as many columns as needed to portray all site conditions. Used to produce aggregate mapunit level (1:1 with mukey) ecological site composition summaries. 
Ecological site conditions have been a recurring theme for me so I am now in this PR considering putting the code I use to boil down ES:mapunit relationships into soilDB.
For example:
``` r
soilDB::get_SDA_coecoclass(method = "all", areasymbols = "CA630") 
#> single result set, returning a data.frame
#>        mukey
#>   1: 1865918
#>   2: 1865926
#>   3: 1865927
#>   4: 1865928
#>   5: 1865929
#>  ---        
#> 124: 2924955
#> 125: 3225132
#> 126: 3225133
#> 127: 3225134
#> 128: 3225135
#> …
```

get_SDA_coecoclass: add `method="all"`

---

R/ISSR800.R
R/mukey-WCS.R

As a proof of concept I use `terra::align()` to adjust results based on known dimensions and extent of the complete CONUS/EPSG:5070 30m data sources.

alignment of WCS results with authoritative grid topology

---

DESCRIPTION
NEWS.md

Draft PR for upcoming 2.8.x release. Plan is to get this out before 22 December (when CRAN goes on winter holiday)
- Sets minimum aqp version v2.0.2 RE: #318, #325

soilDB v2.8.0

---

R/fetchLDM.R
man/fetchLDM.Rd

With https://github.com/ncss-tech/soilDB/commit/47166aed0f80a99acdde0d472d6cf4c2a058bcba can use the `area_type` argument to choose lab data from SSA, country, state, county, MLRA, national forest/park.
For example: get chemical properties for all layers in MLRA 22A:
``` r
x <- fetchLDM("22A", 
what = "area_code", 
area_type = "MLRA", 
tables = "lab_chemical_properties")
#> single result set, returning a data.frame
#> converting profile IDs from integer to character
#> Warning: Horizon bottom depths contain NA! Check depth logic with
#> aqp::checkHzDepthLogic()
x$new_zealand_phosphorus_retent |> 
density(na.rm=T, from=0, to=100) |> 
plot()
```
Closes #294

fetchLDM: add `area_type` argument for non-SSA area queries

---

R/fetchSoilGrids.R
man/fetchSoilGrids.Rd

Will close #202 
As complement to point-based query already provided, provides an option to download the source grids for arbitrary extent. 
For example:
``` r
library(terra)
x <- fetchSDA_spatial("CA630", by.col =  "areasymbol", geom.src = "sapolygon")
#> Using 1 chunks...
#> Chunk #1 completed (n = 1; 0.9 secs)
#> Done in 1.5 secs; mean/chunk: 0.9 secs; mean/symbol: 1.54 secs.
x <- crop(vect(x), ext(x) / 6)
res <- fetchSoilGrids(
x,
grid = TRUE,
filename = "sg_test.tif",
depth_intervals = "5-15",
variables = c("bdod", "cec", "nitrogen", "cfvo"),
summary_type = "Q0.5",
verbose = TRUE
)
#> 0...10...20...30...40...50...60...70...80...90...100 - done.
#> 0...10...20...30...40...50...60...70...80...90...100 - done.
#> 0...10...20...30...40...50...60...70...80...90...100 - …
```

fetchSoilGrids: add `grid` argument for downloading COG subsets for extent

---

R/fetchSoilGrids.R
man/fetchSoilGrids.Rd

- Fix bug in data.frame input (introduced in 2.8.0)
- Requests for more than 5 sites include a call to `Sys.sleep()` to not exceed ISRIC's request "Fair Use" limits (5 / minute)
- Update spatial promotion of SoilProfileCollection for aqp 2.0 (now required on >2.8.0)
- Add 10 kPa (`wv0010`), 33 kPa (`wv0033`), 1500 kPa (`wv1500`) volumetric water content after Turek et al. 2023

`fetchSoilGrids()` updates

---

DESCRIPTION
R/SDA-spatial.R
man/SDA_spatialQuery.Rd

- Allows toggle of `area_ac` column via `geomAcres` argument (default: TRUE for backward compatibility for `method="intersection"`)
- Allows for calculation of `area_ac` for `method = "overlap"` (which was not previously possible)
- Refactor redundant SQL and templating code in `.SDA_geometrySelector()`, which will be further used in updates for #342 
Will close #343

Update and refactor `SDA_spatialQuery()`

---

R/fetchSDA_spatial.R

Addresses `fetchSDA_spatial()` portion of #342
``` r
x <- SDA_query("SELECT DISTINCT areasymbol, mukey FROM mupoint")
#> single result set, returning a data.frame
x
#>   areasymbol   mukey
#> 1      MI606 1717884
#> 2      MI606 1717885
#> 3      MI606 1717886
#> 4      MI606 1717905
#> 5      MI606 1717982
#> 6      MI606 1717983
#> 7      MI606 2378083
#> 8      MI606 2438010
#> 9      MI606 2438011
y <- fetchSDA_spatial(x$mukey[1], geom.src = "mupoint")
#> Using 1 chunks...
#> Chunk #1 completed (n = 1; 0.7 secs)
#> Done in 0.7 secs; mean/chunk: 0.7 secs; mean/symbol: 0.69 secs.
y
#> Simple feature collection with 19 features and 3 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -88.99907 ymin: 47.97266 xmax: -88.63077 ymax: 48.10264
#> …
```

fetchSDA_spatial: Implement `geom.src` `"mupoint"`, `"muline"`, `"featpoint"` and `"featline"` support 

---

R/SDA-spatial.R

Addreses `SDA_spatialQuery()` portion of #342
``` r
b <- fetchSDA_spatial("MI606", geom.src = "SAPOLYGON", method = "bbox")
#> Using 1 chunks...
#> Chunk #1 completed (n = 1; 0.5 secs)
#> Done in 1 secs; mean/chunk: 0.5 secs; mean/symbol: 1.02 secs.
SDA_spatialQuery(b, what = "mupoint")
#> Simple feature collection with 239 features and 1 field
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -89.22762 ymin: 47.8895 xmax: -88.33466 ymax: 48.23765
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>      mukey                       geom
#> 1  1717983  POINT (-88.91737 47.8895)
#> 2  1717983   POINT (-88.91245 47.891)
#> 3  1717983   POINT (-88.9111 47.8914)
#> 4  1717983  POINT (-88.9083 47.89412)
#> 5  1717983 POINT (-88.90718 47.89434)
#> 6  1717983 POINT …
```

SDA_spatialQuery: implement `what` `'mupoint'`, `'muline'`, `'featpoint'`, `'featline'`

---

DESCRIPTION
R/createSSURGO.R
man/createSSURGO.Rd
man/downloadSSURGO.Rd
misc/postgis-ssurgo.Rmd

For a few months I have been exploring the idea of making SSURGO DuckDB databases. 
To further support incorporating this into my workflows, this PR configures `createSSURGO()` to optionally use [{duckdb}](https://duckdb.org/docs/api/r.html) instead of {sf}+{RSQLite}. To toggle on this behavior use `createSSURGO(..., duckdb=TRUE)`.
In the future I would like to develop benchmarks and examples for large database processing--i.e. all of SSURGO in DuckDB vs. Spatialite or Geopackage.

createSSURGO: add support for creating DuckDB and other DBI-compatible databases

---

R/fetchSCAN.R

Closes #14 
**Before:**
``` r
fetchSCAN(site.code = 482, year = 2014)$WTEQ$sensor.id |> 
unique()
#> multiple sensors per site [site 482] PREC.I,PREC.I-2
#> multiple sensors per site [site 482] WTEQ.I,WTEQ.I-2
#> 2921 records (0.19 Mb transferred)
#> [1] WTEQ.I
#> Levels: WTEQ.I
```
**After:**
``` r
fetchSCAN(site.code = 482, year = 2014)$WTEQ$sensor.id |> 
unique()
#> multiple sensors per site [site 482] PREC.I,PREC.I-2
#> multiple sensors per site [site 482] WTEQ.I,WTEQ.I-2
#> 3652 records (0.2 Mb transferred)
#> [1] WTEQ.I   WTEQ.I-2
#> Levels: WTEQ.I WTEQ.I-2
```

fetchSCAN: return all above-ground sensors

---

R/fetchVegdata.R
R/get_vegplot_data_from_NASIS_db.R

siteobsiid absent from a couple tables, including vegplot. Its inclusion should make joining to siteobs easier. 
get_vegplot_speciesbasalarea_from_NASIS() was built in get_vegplot_data_from_NASIS_db.R, but needed to be referenced in fetchVegdata - added this reference.

fetchVegdata: add siteobsiid to vegplot tables; activate vegbasalarea table

---

R/get_NASIS_table_name_by_purpose.R

"plotspeciesbasalarea" and "basalareatreescounted" need to be added to vegetation tables

get_NASIS_table_name_by_purpose: Add basal area tables

---

R/createSSURGO.R
man/createSSURGO.Rd
man/downloadSSURGO.Rd

`createSSURGO()` updates
- Add incremental write of tabular data by table and soil survey area. Much more memory efficient, especially with larger sets of SSAs where tables start to get large.
- Add `maxruledepth` argument, and set default to `0` (reduces number of cointerp rows by 75% for published SSURGO with depth 0 or 1). Generally WSS exports only have max ruledepth 1, but custom NASIS exports can go "deeper"
- Update behavior of `filename` argument when `conn` _DBIConnection_ is specified.
- Add `dissolve_field` argument
- Improve `overwrite` logic
- Add `include_tabular` argument
- Allow `include_spatial` and `include_tabular` to be a _character_ vector of table names (TRUE is all tables, FALSE is no tables)
- Make composite `"soil_metadata"` table, one row per soil survey area

`createSSURGO()` updates

---

NEWS.md
R/AAAA.R
R/fetchNASIS_pedons.R
R/fetchVegdata.R
R/getHzErrorsNASIS.R
R/get_component_data_from_NASIS_db.R
R/get_ecosite_history_from_NASIS_db.R
R/get_hz_data_from_NASIS_db.R
R/get_hz_data_from_pedon_db.R
R/get_site_data_from_NASIS_db.R
R/get_text_notes_from_NASIS_db.R
R/get_veg_data_from_NASIS_db.R
R/get_vegplot_data_from_NASIS_db.R
R/soilDB-package.R
R/utils.R

This PR introduces soft deprecation of aliases to address NASIS portion of https://github.com/ncss-tech/soilDB/issues/242; it supersedes #368 which is a branch that will only be used for testing that various soilDB usages in the wild are working _without_ aliases.
The development and next CRAN release will have warning messages and duplicate columns. In order to ensure that a particular script is compatible with the future removal of aliases, be sure it runs with an install from the "remove-aliases" branch:
```r
remotes::install_github("ncss-tech/soilDB@remove-aliases", dependencies=FALSE)
```
For the deprecation of column aliases, a warning message will be issued the first time an affected function is called in a session. e.g.
```
f <- get_vegplot_from_NASIS_db()
#> …
```

Deprecate NASIS column name aliases

---

R/fetchSRI.R

US Forest Service 'Ecoshare' (https://ecoshare.info) Region 6 Soil Resource Inventory datasets have moved to <https://www.fs.usda.gov/main/ecoshare/datasets/soils> which unfortunately breaks `fetchSRI()` and friends.
Please use the alternative data sources (an ArcGIS Feature Service) available there.
`fetchSRI()` and related functions will be removed in the next minor release (2.9.x)
These functions are "deprecated" but using `stop()` to throw an informative error instead of `.Deprecated()` as they seem to cause my R session to hang indefinitely if I allow them to run. As far as I can tell the original geodatabases are not available from the new fs.usda.gov site.
FYI @joshualerickson

deprecate `fetchSRI()` and related low-level functions

---

R/get_SDA_property.R
R/utils.R

This PR replaces `SELECT ... INTO ...` SQL syntax with Common Table Expressions (CTEs) in `get_SDA_property()`. Temporary tables are used in the dominant component (numeric) and weighted average aggregation methods.
This change has the benefit of increasing the compatibility of `get_SDA_property()` methods with SQLite and other dialects. I've done some benchmarking of old vs. new as well as against SSURGOPortal output. We have 1:1 parity across tools and dialects, and all existing soilDB tests are passing with the new code.
In this PR I've also built out the infrastructure that will make it relatively easy implement this approach for the other areas I identified in #250.
Before merging I will be testing this across the country to verify there aren't edge cases when querying multiple …

get_SDA_property: CTEs for SQLite compatibility and query readability

---

R/SDA-spatial.R
man/SDA_spatialQuery.Rd

- Adds a new argument to `SDA_spatialQuery()` analogous to `fetchSDA_spatial(add.fields)` for adding additional columns to the tabular or spatial results of a spatial query
- Reverts and supersedes #402; which becomes just a specific case of the general solution here
New `addFields` is:
- More extensible (supports many more tables and columns) 
- Backward-compatible (does not introduce issues for folks who already have some custom join workflow)
For example, can now do:
<details>
``` r
bsf <- c(
xmin = -102.04,
ymin = 36.99,
xmax = -101.929,
ymax = 37.138
) |>
sf::st_bbox(crs = "OGC:CRS84") |>
sf::st_as_sfc() |>
sf::st_as_sf()
SDA_spatialQuery(bsf,
what = "areasymbol",
addFields = "tabularversion")
#>   areasymbol tabularversion
#> 1      KS129             21
#> 2 …
```

SDA_spatialQuery: Add `addFields` argument

---

R/get_SDA_coecoclass.R
man/get_SDA_coecoclass.Rd
vignettes/dominant-es.Rmd

This is a draft vignette covering use of Soil Data Access to obtain spatial and tabular data, and the specific use case of creating thematic maps of ecological sites with `SDA_spatialQuery()`, `fetchSDA_spatial()`, and `get_SDA_coecoclass()`
for #157

SSURGO Dominant Ecological Site vignette

---

R/SDA-spatial.R
tests/testthat/test-SDA_query.R

- Fixes for a few combinations of parameters that did not work right in the common table expressions
- Added new tests to cover `geomIntersection` and `addFields` behavior with various geometry sources

fix: SDA_spatialQuery: addFields with `geomIntersection=TRUE` and feat* tables
